Adds a null check
bluehost/endurance-page-cache pull request #121
Opened 2024-03-19 08:41 UTC by arunshenoy99

## Proposed changes

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments
Deprecated: md5): Passing null to
parameter #1 ($string) of type string is deprecated in /app/wordpress/content/mu-
plugins/endurance-page-cache.php on line 763

2024-03-19 10:00 UTC, arunshenoy99 commented
@wpscholar please check if this makes sense.

2024-03-19 13:18 UTC, wpscholar requested changes
@arunshenoy99 I think this makes sense, but let's move it before the `$this->should_update_throttled_items = true;` line. Doing so should shortcut additional processes that happen on shutdown.

2024-03-19 19:07 UTC, wpscholar approved these changes

2024-03-20 22:45 UTC, wpscholar approved these changes

2024-03-25 13:43 UTC, merged